name: Trigger auto deployment for azurefunc-reg-cont

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/azurefunc-reg-cont-AutoDeployTrigger-266d9e38-414a-4b62-ace2-ccf6bfe64149.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREFUNCREGCONT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: azurefuncregistry.azurecr.io
          registryUsername: ${{ secrets.AZUREFUNCREGCONT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZUREFUNCREGCONT_REGISTRY_PASSWORD }}
          containerAppName: azurefunc-reg-cont
          resourceGroup: Sahdev.ai
          imageToBuild: azurefuncregistry.azurecr.io/azurefunc-reg-cont:${{ github.sha }}
          
            

     

